-- Inserção de usuários
INSERT INTO users (name, email, password, is_active, role)
VALUES ('Admin', 'admin@mail.com', '$2y$10$oic4vImnJx2j.dqzU/wYCOx6bYn5bkXqwBJD/mTnu87T3ldYJFcta', true,
        'ADMIN'),
       ('João Silva', 'joao@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Maria Santos', 'maria@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Pedro Almeida', 'pedro@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Ana Oliveira', 'ana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carlos Ferreira', 'carlos@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Mariana Costa', 'mariana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rafaela Souza', 'rafaela@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Fernando Santos', 'fernando@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Patrícia Lima', 'patricia@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Gustavo Oliveira', 'gustavo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Luciana Pereira', 'luciana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Thiago Silva', 'thiago@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carolina Santos', 'carolina@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Ricardo Oliveira', 'ricardo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Juliana Martins', 'juliana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rodrigo Oliveira', 'rodrigo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Aline Martins', 'aline@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Cristiano Silva', 'cristiano@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG',
        true, 'USER'),
       ('Renata Costa', 'renata@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Bruno Santos', 'bruno@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Camila Oliveira', 'camila@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Mateus Lima', 'mateus@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carla Fernandes', 'carla@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rafael Lima', 'rafael@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Tatiane Pereira', 'tatiane@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Gabriel Alves', 'gabriel@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Leonardo Santos', 'leonardo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Vanessa Costa', 'vanessa@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Daniel Oliveira', 'daniel@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER');


-- Inserção de cursos
INSERT INTO courses (name, category)
VALUES ('Fundamentos de Java', 'PROGRAMMING'),
       ('Python para Ciência de Dados', 'DATA_SCIENCE'),
       ('Desenvolvimento Web com React', 'WEB_DEVELOPMENT'),
       ('Essenciais de Aprendizado de Máquina', 'DATA_SCIENCE'),
       ('Desenvolvimento de Aplicativos Móveis', 'MOBILE_DEVELOPMENT'),
       ('Fundamentos de Segurança Cibernética', 'SECURITY'),
       ('Noções Básicas de Computação em Nuvem', 'CLOUD_COMPUTING'),
       ('Princípios de Design de UI/UX', 'DESIGN'),
       ('Fundamentos de Blockchain', 'BLOCKCHAIN'),
       ('Desenvolvimento de Jogos com Unity', 'GAME_DEVELOPMENT'),
       ('Essenciais de DevOps', 'DEVOPS'),
       ('Estratégias de Marketing Digital', 'MARKETING'),
       ('Fundamentos de IoT', 'IOT'),
       ('Análise de Big Data', 'DATA_SCIENCE'),
       ('Gerenciamento Ágil de Projetos', 'PROJECT_MANAGEMENT'),
       ('Desenvolvimento Web com Angular', 'WEB_DEVELOPMENT'),
       ('SQL - Básico ao Avançado', 'BACKEND');

-- Inserção de tópicos
INSERT INTO topicos (title, text, created_at, status, user_id, course_id)
VALUES ('Problemas com Hibernate',
        'Estou tendo problemas ao configurar o Hibernate no meu projeto Spring Boot. Estou enfrentando erros de mapeamento de entidades e não consigo entender por que algumas consultas não estão funcionando corretamente. Alguém pode me ajudar a resolver esses problemas e configurar o Hibernate corretamente?',
        NOW(), 'ABERTO', 7, 1),
       ('Dúvida sobre React Hooks',
        'Qual a diferença entre useState e useEffect em React? Eu sei que ambos são usados para gerenciar estados e efeitos colaterais, mas ainda estou confuso sobre quando exatamente devo usar cada um. Poderiam me dar exemplos práticos para entender melhor?',
        NOW(), 'ABERTO', 2, 3),
       ('Desenvolvimento Android',
        'Quais são as melhores práticas para iniciar no desenvolvimento de aplicativos Android? Estou começando agora e gostaria de dicas sobre as ferramentas que devo usar, como estruturar meu código e evitar problemas comuns.',
        NOW(), 'ABERTO', 3, 5),
       ('Python Pandas',
        'Como manipular DataFrames no Pandas para análise de dados? Preciso de ajuda para entender as operações básicas como seleção, filtragem, agregação e junção de dados. Exemplos práticos seriam muito úteis.',
        NOW(), 'ABERTO', 4, 2),
       ('Angular Component Lifecycle',
        'Como funciona o ciclo de vida dos componentes no Angular? Gostaria de entender melhor quando e por que cada método do ciclo de vida é chamado, e como posso usá-los para gerenciar o estado e o comportamento dos meus componentes.',
        NOW(), 'ABERTO', 5, 16),
       ('Problemas com transações no Hibernate',
        'Como posso resolver problemas de commit e rollback em transações no Hibernate? Estou tendo dificuldades para garantir que minhas transações sejam concluídas corretamente e gostaria de saber mais sobre como gerenciar transações de forma eficaz.',
        NOW(), 'ABERTO', 6, 1),
       ('React Redux Example',
        'Alguém pode me mostrar um exemplo prático de como usar Redux com React? Estou tentando entender como gerenciar o estado global da minha aplicação e integrar Redux com meus componentes React de forma eficiente.',
        NOW(), 'ABERTO', 7, 3),
       ('Desenvolvimento de aplicativos iOS',
        'Quais são as melhores práticas para desenvolver aplicativos iOS de forma eficiente? Estou procurando dicas sobre o uso de Swift, gerenciamento de memória, design de interfaces e otimização de performance.',
        NOW(), 'ABERTO', 8, 5),
       ('Análise de dados com Python',
        'Quais são as principais técnicas de análise de dados utilizando Python? Estou interessado em saber mais sobre bibliotecas como NumPy, Pandas e Matplotlib, e como posso usá-las para realizar análises estatísticas e visualizações de dados.',
        NOW(), 'ABERTO', 9, 2),
       ('Angular Forms',
        'Como posso criar e validar formulários complexos com Reactive Forms no Angular? Preciso de ajuda para entender como construir formulários dinâmicos, aplicar validações personalizadas e gerenciar o estado dos formulários.',
        NOW(), 'ABERTO', 10, 16),
       ('Erros comuns em consultas SQL',
        'Quais são os erros mais comuns em consultas SQL e como posso evitá-los? Estou tendo dificuldades com algumas consultas complexas e gostaria de saber mais sobre práticas recomendadas e técnicas de otimização.',
        NOW(), 'ABERTO', 11, 17),
       ('React Performance Optimization',
        'Como posso otimizar a performance de minhas aplicações React? Gostaria de dicas sobre como evitar re-renderizações desnecessárias, usar memoização, e outras técnicas para melhorar a velocidade e responsividade da minha aplicação.',
        NOW(), 'ABERTO', 12, 3),
       ('Desenvolvimento de aplicativos Android avançado',
        'Quais são alguns recursos avançados para desenvolvimento de apps Android? Estou interessado em aprender sobre otimização de performance, uso de serviços em segundo plano, e integração com APIs complexas.',
        NOW(), 'ABERTO', 13, 5),
       ('Machine Learning com Python',
        'Quais bibliotecas Python são recomendadas para iniciantes em Machine Learning? Estou começando a estudar aprendizado de máquina e gostaria de saber mais sobre bibliotecas como scikit-learn, TensorFlow e Keras, e como usá-las em projetos práticos.',
        NOW(), 'ABERTO', 14, 4),
       ('Angular Routing',
        'Como configurar rotas dinâmicas e proteger rotas com guardas no Angular? Estou tentando criar uma aplicação com navegação complexa e preciso de ajuda para entender como configurar e gerenciar rotas de forma eficiente.',
        NOW(), 'ABERTO', 15, 16),
       ('Introdução à Programação Java',
        'Alguém pode explicar a sintaxe básica e os conceitos fundamentais do Java? Estou começando a aprender programação e gostaria de entender melhor como escrever e executar programas simples em Java.',
        '2023-06-15 10:30:00', 'ABERTO', 1, 1),
       ('Análise de Dados',
        'Quais métodos posso usar para análise de dados com Python? Estou explorando diferentes técnicas de análise e gostaria de exemplos sobre como usar bibliotecas como Pandas e Matplotlib para manipular e visualizar dados.',
        '2023-06-16 11:45:00', 'ABERTO', 2, 2),
       ('Ciclo de Vida dos Componentes React',
        'Como funcionam os métodos do ciclo de vida em componentes React? Estou confuso sobre quando usar componentDidMount, componentDidUpdate, e outros métodos, e gostaria de entender como eles afetam o comportamento dos meus componentes.',
        '2023-06-17 12:00:00', 'ABERTO', 3, 3),
       ('Aprendizado de Máquina',
        'Quais são os principais algoritmos de aprendizado de máquina? Gostaria de uma visão geral dos algoritmos mais utilizados, como regressão linear, árvores de decisão e redes neurais, e exemplos de quando usá-los.',
        '2023-06-18 13:15:00', 'ABERTO', 4, 4),
       ('Desenvolvimento de Apps iOS',
        'Como começar a desenvolver apps iOS usando Swift? Estou procurando recursos e tutoriais para iniciantes, incluindo configuração do ambiente de desenvolvimento, conceitos básicos de Swift, e construção de interfaces de usuário.',
        '2023-06-19 14:30:00', 'ABERTO', 5, 5),
       ('Segurança Cibernética',
        'Quais são as ameaças comuns de segurança cibernética e como me proteger? Estou preocupado com a segurança das minhas aplicações web e gostaria de entender mais sobre vulnerabilidades como SQL Injection, XSS e como mitigar esses riscos.',
        '2023-06-20 15:45:00', 'ABERTO', 6, 6),
       ('Computação em Nuvem',
        'Quais são os conceitos básicos e serviços na computação em nuvem? Estou interessado em aprender sobre provedores de nuvem como AWS, Azure e Google Cloud, e como usar serviços como armazenamento, computação e bancos de dados na nuvem.',
        '2023-06-21 16:00:00', 'ABERTO', 7, 7),
       ('Design de Interface de Usuário',
        'Quais são os princípios fundamentais de design de interface de usuário? Estou desenvolvendo uma aplicação web e gostaria de dicas sobre como criar interfaces intuitivas e agradáveis para os usuários.',
        '2023-06-22 17:15:00', 'ABERTO', 8, 8),
       ('Blockchain',
        'Como funciona a tecnologia blockchain e quais são seus casos de uso? Gostaria de entender os conceitos básicos de blockchain, incluindo como as transações são registradas e verificadas, e exemplos de aplicações práticas dessa tecnologia.',
        '2023-06-23 18:30:00', 'ABERTO', 9, 9),
       ('Desenvolvimento de Jogos com Unity',
        'Como posso começar no desenvolvimento de jogos usando Unity? Estou interessado em criar jogos 2D e 3D e gostaria de saber mais sobre a configuração do ambiente, scripting com C#, e recursos disponíveis no Unity.',
        '2023-06-24 19:45:00', 'ABERTO', 10, 10),
       ('DevOps',
        'Quais são os princípios e práticas do DevOps? Gostaria de entender melhor como implementar integração contínua e entrega contínua (CI/CD), automatizar deploys e gerenciar infraestrutura como código.',
        '2023-06-25 20:00:00', 'ABERTO', 11, 11),
       ('Marketing Digital',
        'Quais são as estratégias e técnicas eficazes de marketing digital? Estou buscando maneiras de aumentar a visibilidade da minha marca online e gostaria de aprender mais sobre SEO, marketing de conteúdo e campanhas de mídia social.',
        '2023-06-26 21:15:00', 'ABERTO', 12, 12),
       ('IoT',
        'Quais são as aplicações e casos de uso de IoT? Gostaria de saber mais sobre como dispositivos IoT são utilizados em diferentes indústrias, os desafios de segurança e privacidade, e como começar a desenvolver projetos de IoT.',
        '2023-06-27 22:30:00', 'ABERTO', 13, 13),
       ('Big Data',
        'Quais técnicas e ferramentas são usadas para análise de big data? Estou explorando métodos de processamento de grandes volumes de dados e gostaria de entender melhor como usar ferramentas como Hadoop e Spark para análises eficientes.',
        '2023-06-28 23:45:00', 'ABERTO', 14, 14),
       ('Gerenciamento Ágil de Projetos',
        'Quais são os princípios e metodologias do gerenciamento ágil de projetos? Gostaria de saber mais sobre como implementar Scrum e Kanban, e como essas metodologias podem melhorar a eficiência e colaboração da equipe.',
        '2023-06-29 00:00:00', 'ABERTO', 15, 15);


-- Inserção de comentários
INSERT INTO comments (text, topic_id, created_at, user_id, solution)
VALUES ('Você verificou as configurações do seu persistence.xml? Muitas vezes, problemas de configuração estão relacionados a propriedades ausentes ou incorretamente definidas. Certifique-se de que todas as entidades estão devidamente mapeadas e que as informações de conexão com o banco de dados, como URL, nome de usuário e senha, estão corretas. Além disso, verifique se o Hibernate Dialect está corretamente configurado para o seu tipo de banco de dados.',
        1, NOW(), 2, false),
       ('useState é um Hook que permite adicionar estado a componentes funcionais. Você pode usá-lo para declarar variáveis de estado dentro do seu componente. Por outro lado, useEffect é usado para lidar com efeitos colaterais, como chamadas de API, assinaturas de eventos, ou manipulações diretas de DOM. Este Hook é executado após cada renderização do componente, tornando-o ideal para sincronizar o estado do componente com fontes de dados externas.',
        2, NOW(), 1, false),
       ('Para começar com o desenvolvimento Android, recomendo estudar a estrutura básica de um projeto Android, que inclui atividades, fragments e layouts XML. Familiarize-se com o Android Studio, a principal IDE para desenvolvimento Android. Aprenda a navegar e utilizar suas ferramentas, como o emulador e o Logcat. Além disso, entender o ciclo de vida das atividades e como gerenciar diferentes configurações de tela é essencial para criar aplicativos robustos.',
        3, NOW(), 3, false),
       ('Pandas é uma biblioteca essencial para manipulação e análise de dados em Python. Ela oferece estruturas de dados como DataFrames, que permitem armazenar e manipular dados tabulares de forma eficiente. Com Pandas, você pode realizar operações como seleção, filtragem, agregação e limpeza de dados de maneira rápida e intuitiva. Além disso, a integração com outras bibliotecas como NumPy e Matplotlib facilita a execução de análises estatísticas e a criação de visualizações.',
        4, NOW(), 4, false),
       ('Entender o ciclo de vida dos componentes no Angular é crucial para desenvolver aplicações eficientes e responsivas. O ciclo de vida inclui fases como criação, atualização e destruição de componentes. Cada fase tem eventos específicos, como ngOnInit e ngOnDestroy, que permitem executar lógica personalizada. Por exemplo, você pode inicializar dados no ngOnInit e liberar recursos no ngOnDestroy, garantindo que seu aplicativo funcione de forma otimizada.',
        5, NOW(), 5, false),
       ('Para configurar corretamente as transações no Hibernate, é fundamental definir a estratégia de gerenciamento de transações (JTA ou resource-local) no arquivo de configuração. Certifique-se de que as propriedades de transação, como o nível de isolamento e a política de commit, estão configuradas de acordo com os requisitos do seu projeto. Além disso, verifique se o gerenciador de transações está corretamente integrado ao seu contêiner ou framework de injeção de dependência.',
        6, NOW(), 6, false),
       ('O uso do Redux pode simplificar significativamente a gerência de estado em aplicações React, especialmente em projetos de grande porte. Ele centraliza todo o estado da aplicação em um único store, permitindo um fluxo de dados previsível e fácil de depurar. Ao utilizar actions e reducers, você pode definir como o estado deve ser atualizado em resposta a diferentes eventos, garantindo que a lógica de negócio esteja desacoplada dos componentes de UI.',
        7, NOW(), 7, false),
       ('Para desenvolver aplicativos iOS, é importante ter uma boa compreensão do Swift, a linguagem de programação da Apple. Além disso, familiarizar-se com as diretrizes de design da Apple garante que seus aplicativos sejam intuitivos e consistentes com o ecossistema iOS. Aprender sobre o gerenciamento de memória, o uso de ViewControllers e a integração com APIs do iOS permitirá que você crie aplicativos eficientes e de alta qualidade.',
        8, NOW(), 8, false),
       ('Python oferece muitas bibliotecas poderosas para análise de dados. Pandas é ideal para manipulação de dados tabulares, permitindo leitura e transformação de dados de diversas fontes. NumPy fornece suporte para operações matemáticas e arrays multidimensionais. Juntas, essas bibliotecas facilitam a execução de análises estatísticas complexas e a criação de visualizações detalhadas com Matplotlib, tornando Python uma escolha popular para cientistas de dados.',
        9, NOW(), 9, false),
       ('Os formulários são uma parte essencial do desenvolvimento web com Angular. Utilizando Reactive Forms, você pode criar formulários dinâmicos que oferecem validações complexas e feedback ao usuário em tempo real. Com a abordagem reativa, você pode monitorar o estado do formulário, reagir a alterações e manipular dados de forma eficiente. Isso garante que os formulários sejam robustos e proporcionem uma boa experiência ao usuário.',
        10, NOW(), 7, false),
       ('Verifique se você está usando a versão correta do Hibernate e se todas as dependências necessárias estão incluídas no seu arquivo pom.xml ou build.gradle. Problemas de versão ou dependências faltantes podem causar erros de configuração. Além disso, certifique-se de que o arquivo hibernate.cfg.xml está no local correto e devidamente configurado.',
        1, NOW(), 6, false),
       ('Além do persistence.xml, verifique as propriedades específicas do Hibernate no arquivo de configuração. Propriedades como hibernate.hbm2ddl.auto, hibernate.show_sql e hibernate.format_sql podem impactar o comportamento da sua aplicação. Garanta que a configuração do pool de conexões também está correta.',
        1, NOW(), 7, false),
       ('useState e useEffect são fundamentais no React. useState permite que você adicione estado local a componentes funcionais, enquanto useEffect permite executar efeitos colaterais, como fetch de dados, subscrições ou manipulações de DOM, após renderizações. Lembre-se de que useEffect pode retornar uma função de limpeza para lidar com efeitos que precisam ser desmontados.',
        2, NOW(), 8, false),
       ('Enfrentei um problema semelhante na semana passada.', 2, NOW(), 9, false),
       ('Para iniciar no desenvolvimento Android, além de entender a estrutura do projeto, é útil aprender sobre os componentes principais como Intents, Services e Broadcast Receivers. Além disso, estudar o Material Design ajudará a criar interfaces que seguem as diretrizes de design do Google, proporcionando uma melhor experiência ao usuário.',
        3, '2023-06-17 16:15:00', 10, false),
       ('Além de se familiarizar com o Android Studio, é importante entender o conceito de RecyclerView para exibir listas de dados de forma eficiente e aprender sobre os diferentes tipos de layout disponíveis, como ConstraintLayout e LinearLayout, para criar interfaces responsivas.',
        3, '2023-06-17 17:30:00', 11, false),
       ('Pandas permite operações avançadas de manipulação de dados, como mesclagem, junção e pivotagem de DataFrames. Isso é especialmente útil para combinar dados de várias fontes ou transformar dados para análise. Além disso, a integração com bibliotecas de visualização como Matplotlib e Seaborn facilita a criação de gráficos e plots diretamente a partir dos DataFrames.',
        4, '2023-06-18 18:45:00', 12, false),
       ('Pandas facilita a manipulação de grandes conjuntos de dados através de técnicas como groupby, que permite agrupar dados e realizar operações agregadas, como soma, média e contagem. Isso é extremamente útil para resumir e analisar grandes volumes de dados de maneira eficiente.',
        4, '2023-06-18 20:00:00', 13, false),
       ('O ciclo de vida dos componentes no Angular inclui fases como OnInit, OnChanges e OnDestroy. Cada fase permite que você implemente lógica específica para inicialização, detecção de mudanças e limpeza de recursos. Compreender essas fases ajuda a criar componentes mais eficientes e a evitar vazamentos de memória.',
        5, '2023-06-19 21:15:00', 14, false),
       ('No Angular, os hooks de ciclo de vida como ngOnChanges permitem detectar e reagir a mudanças em inputs, enquanto ngOnDestroy é utilizado para limpar assinaturas e outros recursos alocados. Isso ajuda a manter a aplicação performática e evitar problemas de desempenho.',
        5, '2023-06-19 22:30:00', 15, false),
       ('Certifique-se de que suas transações estão configuradas para rollback em caso de falhas. No Hibernate, você pode usar anotações como @Transactional para gerenciar automaticamente o início e o commit das transações. Verifique também se o gerenciador de transações está configurado corretamente em seu contêiner de injeção de dependência.',
        6, '2023-06-20 23:45:00', 16, false),
       ('Além da configuração básica, é importante monitorar as transações para identificar possíveis gargalos. Utilizar ferramentas de monitoramento de desempenho e logs pode ajudar a diagnosticar e resolver problemas de transação no Hibernate, garantindo que os commits e rollbacks estejam sendo executados conforme esperado.',
        6, '2023-06-21 01:00:00', 17, false),
       ('Redux ajuda a gerenciar o estado global da aplicação de forma centralizada. Cada mudança de estado é previsível e rastreável através de actions e reducers. Isso facilita a depuração e manutenção da aplicação, especialmente quando ela cresce em complexidade.',
        7, '2023-06-21 02:15:00', 18, false),
       ('Ao usar Redux, é importante estruturar bem suas actions e reducers para manter a lógica de estado organizada. Utilizar middlewares como Redux Thunk ou Redux Saga pode ajudar a gerenciar operações assíncronas e efeitos colaterais, melhorando a eficiência do fluxo de dados na aplicação.',
        7, '2023-06-22 03:30:00', 19, false),
       ('Para desenvolver aplicativos iOS de forma eficiente, é fundamental entender o uso de Auto Layout para criar interfaces responsivas que se adaptam a diferentes tamanhos de tela. Além disso, aprender sobre o gerenciamento de ciclo de vida das views e a arquitetura MVC (Model-View-Controller) é essencial para criar aplicativos bem estruturados.',
        8, '2023-06-22 04:45:00', 20, false),
       ('Além de dominar Swift, familiarize-se com as APIs da Apple, como CoreData para persistência de dados e CoreGraphics para manipulação de gráficos. Entender o uso de notificações e delegação é crucial para criar aplicativos interativos e responsivos.',
        8, '2023-06-23 06:00:00', 21, false),
       ('Eu também enfrentei problemas similares ao configurar o Hibernate. Verifique se suas entidades estão mapeadas corretamente e se você configurou o data source adequadamente.',
        7, NOW(), 1, false),
       ('Para entender a diferença entre useState e useEffect, lembre-se que useState é usado para gerenciar estados locais, enquanto useEffect é usado para gerenciar efeitos colaterais, como chamadas de API.',
        2, NOW(), 2, false),
       ('Para iniciar no desenvolvimento de aplicativos Android, recomendo começar com o Android Studio e seguir tutoriais básicos. Ferramentas como Kotlin e Jetpack podem ser úteis.',
        3, NOW(), 3, false),
       ('No Pandas, você pode selecionar colunas específicas de um DataFrame usando df[["coluna1", "coluna2"]]. Para filtrar dados, use df[df["coluna"] > valor].',
        4, NOW(), 4, false),
       ('O ciclo de vida dos componentes no Angular inclui métodos como ngOnInit, ngOnChanges, e ngOnDestroy, que são usados para inicializar, atualizar e limpar componentes, respectivamente.',
        5, NOW(), 5, false),
       ('Para resolver problemas de commit e rollback em transações no Hibernate, assegure-se de usar @Transactional e gerenciar as transações corretamente no código.',
        6, NOW(), 6, false),
       ('Aqui está um exemplo simples de Redux com React: configure seu store com combineReducers e forneça o store ao aplicativo com o Provider do React Redux.',
        7, NOW(), 7, false),
       ('Para desenvolver aplicativos iOS de forma eficiente, familiarize-se com o Xcode e o Swift. Use as melhores práticas de gerenciamento de memória e otimização de performance.',
        8, NOW(), 8, false),
       ('Para análise de dados com Python, utilize NumPy para operações numéricas, Pandas para manipulação de dados, e Matplotlib para visualização. Estes são fundamentais para qualquer análise.',
        9, NOW(), 9, false),
       ('Com Reactive Forms no Angular, você pode criar formulários dinâmicos e aplicar validações personalizadas. Use FormGroup e FormControl para gerenciar o estado do formulário.',
        10, NOW(), 10, false),
       ('Erros comuns em consultas SQL incluem uso incorreto de JOINs, falta de índices, e subconsultas ineficientes. Sempre otimize suas consultas e use EXPLAIN para analisar a performance.',
        11, NOW(), 11, false),
       ('Para otimizar a performance de aplicações React, use React.memo para evitar re-renderizações desnecessárias e React Profiler para identificar gargalos de performance.',
        12, NOW(), 12, false),
       ('Recursos avançados no desenvolvimento de apps Android incluem o uso de coroutines para operações assíncronas, WorkManager para tarefas em segundo plano, e Retrofit para chamadas de API.',
        13, NOW(), 13, false),
       ('Para iniciantes em Machine Learning, bibliotecas como scikit-learn são excelentes para começar. Elas fornecem implementações simples de algoritmos de aprendizado supervisionado e não supervisionado.',
        14, NOW(), 14, false),
       ('Para configurar rotas dinâmicas e proteger rotas com guardas no Angular, use o módulo RouterModule e implementa guardas com CanActivate para verificar a autorização do usuário.',
        15, NOW(), 15, false);

