-- Inserção de usuários
INSERT INTO users (name, email, password, is_active, role)
VALUES ('Admin', 'admin@mail.com', '$2y$10$oic4vImnJx2j.dqzU/wYCOx6bYn5bkXqwBJD/mTnu87T3ldYJFcta', true,
        'USER'),
       ('João Silva', 'joao@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Maria Santos', 'maria@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Pedro Almeida', 'pedro@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Ana Oliveira', 'ana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carlos Ferreira', 'carlos@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Mariana Costa', 'mariana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rafaela Souza', 'rafaela@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Fernando Santos', 'fernando@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Patrícia Lima', 'patricia@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Gustavo Oliveira', 'gustavo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Luciana Pereira', 'luciana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Thiago Silva', 'thiago@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carolina Santos', 'carolina@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Ricardo Oliveira', 'ricardo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Juliana Martins', 'juliana@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rodrigo Oliveira', 'rodrigo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Aline Martins', 'aline@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Cristiano Silva', 'cristiano@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG',
        true, 'USER'),
       ('Renata Costa', 'renata@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Bruno Santos', 'bruno@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Camila Oliveira', 'camila@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Mateus Lima', 'mateus@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carla Fernandes', 'carla@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rafael Lima', 'rafael@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Tatiane Pereira', 'tatiane@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Gabriel Alves', 'gabriel@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Leonardo Santos', 'leonardo@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Vanessa Costa', 'vanessa@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Daniel Oliveira', 'daniel@mail.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER');


-- Inserção de cursos
INSERT INTO courses (name, category)
VALUES ('Fundamentos de Java', 'PROGRAMMING'),
       ('Python para Ciência de Dados', 'DATA_SCIENCE'),
       ('Desenvolvimento Web com React', 'WEB_DEVELOPMENT'),
       ('Essenciais de Aprendizado de Máquina', 'DATA_SCIENCE'),
       ('Desenvolvimento de Aplicativos Móveis', 'MOBILE_DEVELOPMENT'),
       ('Fundamentos de Segurança Cibernética', 'SECURITY'),
       ('Noções Básicas de Computação em Nuvem', 'CLOUD_COMPUTING'),
       ('Princípios de Design de UI/UX', 'DESIGN'),
       ('Fundamentos de Blockchain', 'BLOCKCHAIN'),
       ('Desenvolvimento de Jogos com Unity', 'GAME_DEVELOPMENT'),
       ('Essenciais de DevOps', 'DEVOPS'),
       ('Estratégias de Marketing Digital', 'MARKETING'),
       ('Fundamentos de IoT', 'IOT'),
       ('Análise de Big Data', 'DATA_SCIENCE'),
       ('Gerenciamento Ágil de Projetos', 'PROJECT_MANAGEMENT'),
       ('Desenvolvimento Web com Angular', 'WEB_DEVELOPMENT'),
       ('SQL - Básico ao Avançado', 'BACKEND');

-- Inserção de tópicos
INSERT INTO topicos (title, text, created_at, status, user_id, course_id)
VALUES ('Problemas com Hibernate', 'Estou tendo problemas ao configurar o Hibernate no meu projeto Spring Boot.', NOW(),
        'ABERTO', 7, 1),
       ('Dúvida sobre React Hooks', 'Qual a diferença entre useState e useEffect em React?', NOW(), 'ABERTO', 2, 2),
       ('Desenvolvimento Android', 'Dicas para iniciar no desenvolvimento de aplicativos Android?', NOW(), 'ABERTO', 3,
        5),
       ('Python Pandas Tutorial', 'Tutorial básico sobre o uso de Pandas para análise de dados.', NOW(), 'ABERTO', 4,
        2),
       ('Angular Component Lifecycle', 'Entendendo o ciclo de vida dos componentes no Angular.', NOW(), 'ABERTO', 5, 16),
       ('Problemas com transações no Hibernate', 'Como resolver problemas de transações no Hibernate?', NOW(), 'ABERTO',
        6, 1),
       ('React Redux Example', 'Exemplo prático de uso do Redux com React.', NOW(), 'ABERTO', 7, 3),
       ('Desenvolvimento de aplicativos iOS', 'Dicas e truques para desenvolver aplicativos iOS de forma eficiente.',
        NOW(), 'ABERTO', 8, 5),
       ('Análise de dados com Python', 'Principais técnicas de análise de dados utilizando Python.', NOW(), 'ABERTO', 9,
        2),
       ('Angular Forms Tutorial', 'Tutorial completo sobre formulários no Angular.', NOW(), 'ABERTO', 10, 16),
       ('Erros comuns em consultas SQL', 'Principais erros cometidos em consultas SQL e como evitá-los.', NOW(),
        'ABERTO', 11, 17),
       ('React Performance Optimization', 'Dicas para otimização de performance em aplicações React.', NOW(), 'ABERTO',
        12, 3),
       ('Desenvolvimento de aplicativos Android avançado',
        'Explorando recursos avançados para desenvolvimento de apps Android.', NOW(), 'ABERTO', 13, 5),
       ('Machine Learning com Python', 'Introdução ao Machine Learning usando Python e bibliotecas populares.', NOW(),
        'ABERTO', 14, 4),
       ('Angular Routing Guide', 'Guia completo sobre roteamento no Angular.', NOW(), 'ABERTO', 15, 16),
       ('Introdução à Programação Java', 'Discussão sobre a sintaxe básica e conceitos fundamentais do Java.',
        '2023-06-15 10:30:00', 'ABERTO', 1, 1),
       ('Técnicas de Análise de Dados', 'Explorando vários métodos de análise de dados com Python.',
        '2023-06-16 11:45:00',
        'ABERTO', 2, 2),
       ('Ciclo de Vida dos Componentes React', 'Entendendo os métodos do ciclo de vida em componentes React.',
        '2023-06-17 12:00:00', 'ABERTO', 3, 3),
       ('Introdução ao Aprendizado de Máquina', 'Visão geral dos algoritmos e aplicações de aprendizado de máquina.',
        '2023-06-18 13:15:00', 'ABERTO', 4, 4),
       ('Noções Básicas de Desenvolvimento de Apps iOS', 'Início no desenvolvimento de apps iOS usando Swift.',
        '2023-06-19 14:30:00', 'ABERTO', 5, 5),
       ('Visão Geral das Ameaças de Segurança Cibernética',
        'Discussão sobre ameaças comuns de segurança cibernética e defesas.',
        '2023-06-20 15:45:00', 'ABERTO', 6, 6),
       ('Introdução à Computação em Nuvem', 'Conceitos básicos e serviços na computação em nuvem.',
        '2023-06-21 16:00:00',
        'ABERTO', 7, 7),
       ('Princípios de Design de Interface de Usuário', 'Princípios fundamentais de design de interface de usuário.',
        '2023-06-22 17:15:00', 'ABERTO', 8, 8),
       ('Visão Geral da Tecnologia Blockchain', 'Exploração da tecnologia blockchain e seus casos de uso.',
        '2023-06-23 18:30:00',
        'ABERTO', 9, 9),
       ('Noções Básicas do Desenvolvimento de Jogos com Unity', 'Início no desenvolvimento de jogos usando Unity.',
        '2023-06-24 19:45:00', 'ABERTO', 10, 10),
       ('Introdução ao DevOps', 'Entendendo os princípios e práticas do DevOps.', '2023-06-25 20:00:00', 'ABERTO', 11,
        11),
       ('Estratégias de Marketing Digital', 'Estratégias e técnicas eficazes de marketing digital.',
        '2023-06-26 21:15:00',
        'ABERTO', 12, 12),
       ('Aplicações e Casos de Uso de IoT', 'Exploração de aplicações e casos de uso de IoT.', '2023-06-27 22:30:00',
        'ABERTO', 13, 13),
       ('Técnicas de Análise de Big Data', 'Técnicas e ferramentas para análise de big data.', '2023-06-28 23:45:00',
        'ABERTO',
        14, 14),
       ('Princípios de Gerenciamento Ágil de Projetos', 'Princípios e metodologias do gerenciamento ágil de projetos.',
        '2023-06-29 00:00:00', 'ABERTO', 15, 15);

-- Inserção de comentários
INSERT INTO comments (text, topic_id, created_at, user_id, solution)
VALUES ('Você verificou as configurações do seu persistence.xml?', 1, NOW(), 2, false),
       ('useState é usado para gerenciar estado em componentes funcionais, enquanto useEffect é usado para efeitos colaterais.',
        2, NOW(), 1, false),
       ('Recomendo estudar a estrutura básica de um projeto Android e explorar o Android Studio.', 3, NOW(), 3, false),
       ('Pandas é uma poderosa biblioteca para manipulação e análise de dados em Python.', 4, NOW(), 4, false),
       ('O ciclo de vida dos componentes no Angular é fundamental para entender como a aplicação funciona.', 5, NOW(),
        5, false),
       ('Certifique-se de configurar corretamente as transações no arquivo de configuração do Hibernate.', 6, NOW(), 6,
        false),
       ('Redux pode melhorar a gerência de estado em aplicações React de grande porte.', 7, NOW(), 7, false),
       ('O desenvolvimento de aplicativos iOS requer familiaridade com Swift e as diretrizes da Apple.', 8, NOW(), 8,
        false),
       ('Python oferece muitas bibliotecas poderosas para análise de dados, como Pandas e NumPy.', 9, NOW(), 9, false),
       ('Formulários são uma parte essencial do desenvolvimento web com Angular.', 10, NOW(), 7, false),
       ('Ótima explicação, obrigado!', 1, '2023-06-15 11:00:00', 6, false),
       ('Eu tenho uma pergunta sobre herança em Java.', 1, '2023-06-15 12:30:00', 7, false),
       ('Como posso otimizar este algoritmo?', 2, '2023-06-16 13:45:00', 8, false),
       ('Enfrentei um problema semelhante na semana passada.', 2, '2023-06-16 15:00:00', 9, false),
       ('React é adequado para aplicações de grande porte?', 3, '2023-06-17 16:15:00', 10, false),
       ('Você pode explicar o fluxo de trabalho do Redux?', 3, '2023-06-17 17:30:00', 11, false),
       ('Implementei SVM para um projeto recentemente.', 4, '2023-06-18 18:45:00', 12, false),
       ('Quais são os pré-requisitos para aprendizado de máquina?', 4, '2023-06-18 20:00:00', 13, false),
       ('Como você lida com gerenciamento de memória em aplicativos iOS?', 5, '2023-06-19 21:15:00', 14, false),
       ('Discutindo medidas de segurança no desenvolvimento de aplicativos.', 5, '2023-06-19 22:30:00', 15, false),
       ('Como você detecta tentativas de phishing?', 6, '2023-06-20 23:45:00', 16, false),
       ('Quais são as vantagens de usar serviços de nuvem?', 6, '2023-06-21 01:00:00', 17, false),
       ('Tenho uma pergunta sobre princípios de design UX.', 7, '2023-06-21 02:15:00', 18, false),
       ('Como o blockchain garante a integridade dos dados?', 7, '2023-06-22 03:30:00', 19, false),
       ('Dicas para otimizar o desempenho do jogo no Unity?', 8, '2023-06-22 04:45:00', 20, false),
       ('Discutindo pipelines CI/CD no DevOps.', 8, '2023-06-23 06:00:00', 21, false);
