-- Inserção de usuários
INSERT INTO users (name, email, password, is_active, role)
VALUES ('João Silva', 'joao@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'ADMIN'),
       ('Maria Santos', 'maria@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Pedro Almeida', 'pedro@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Ana Oliveira', 'ana@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carlos Ferreira', 'carlos@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Mariana Costa', 'mariana@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rafaela Souza', 'rafaela@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Fernando Santos', 'fernando@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'ADMIN'),
       ('Patrícia Lima', 'patricia@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Gustavo Oliveira', 'gustavo@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Luciana Pereira', 'luciana@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Thiago Silva', 'thiago@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carolina Santos', 'carolina@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Ricardo Oliveira', 'ricardo@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Juliana Martins', 'juliana@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rodrigo Oliveira', 'rodrigo@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Aline Martins', 'aline@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Cristiano Silva', 'cristiano@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG',
        true, 'USER'),
       ('Renata Costa', 'renata@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Bruno Santos', 'bruno@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Camila Oliveira', 'camila@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Mateus Lima', 'mateus@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Carla Fernandes', 'carla@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Rafael Lima', 'rafael@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Tatiane Pereira', 'tatiane@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Gabriel Alves', 'gabriel@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Patrícia Oliveira', 'patricia@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG',
        true, 'USER'),
       ('Leonardo Santos', 'leonardo@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Vanessa Costa', 'vanessa@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Daniel Oliveira', 'daniel@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER'),
       ('Mariana Almeida', 'mariana@example.com', '$2a$10$XKN67XQ0gIKv/DpD1h6e3uBjv9ySHXBrfMolHhHrWxW1DJVJ27RaG', true,
        'USER');

-- Inserção de cursos
INSERT INTO courses (name, category)
VALUES ('Java Fundamentals', 'PROGRAMMING'),
       ('Python for Data Science', 'DATA_SCIENCE'),
       ('Web Development with React', 'WEB_DEVELOPMENT'),
       ('Machine Learning Essentials', 'DATA_SCIENCE'),
       ('Mobile App Development', 'MOBILE_DEVELOPMENT'),
       ('Cybersecurity Fundamentals', 'SECURITY'),
       ('Cloud Computing Basics', 'CLOUD_COMPUTING'),
       ('UI/UX Design Principles', 'DESIGN'),
       ('Blockchain Fundamentals', 'BLOCKCHAIN'),
       ('Game Development with Unity', 'GAME_DEVELOPMENT'),
       ('DevOps Essentials', 'DEVOPS'),
       ('Digital Marketing Strategies', 'MARKETING'),
       ('IoT Fundamentals', 'IOT'),
       ('Big Data Analytics', 'DATA_SCIENCE'),
       ('Agile Project Management', 'PROJECT_MANAGEMENT');

-- Inserção de tópicos
INSERT INTO topicos (title, text, created_at, status, user_id, course_id)
VALUES ('Problemas com Hibernate', 'Estou tendo problemas ao configurar o Hibernate no meu projeto Spring Boot.', NOW(),
        'ABERTO', 1, 1),
       ('Dúvida sobre React Hooks', 'Qual a diferença entre useState e useEffect em React?', NOW(), 'ABERTO', 2, 2),
       ('Desenvolvimento Android', 'Dicas para iniciar no desenvolvimento de aplicativos Android?', NOW(), 'ABERTO', 3,
        3),
       ('Python Pandas Tutorial', 'Tutorial básico sobre o uso de Pandas para análise de dados.', NOW(), 'ABERTO', 4,
        4),
       ('Angular Component Lifecycle', 'Entendendo o ciclo de vida dos componentes no Angular.', NOW(), 'ABERTO', 5, 5),
       ('Problemas com transações no Hibernate', 'Como resolver problemas de transações no Hibernate?', NOW(), 'ABERTO',
        6, 1),
       ('React Redux Example', 'Exemplo prático de uso do Redux com React.', NOW(), 'ABERTO', 7, 2),
       ('Desenvolvimento de aplicativos iOS', 'Dicas e truques para desenvolver aplicativos iOS de forma eficiente.',
        NOW(), 'ABERTO', 8, 3),
       ('Análise de dados com Python', 'Principais técnicas de análise de dados utilizando Python.', NOW(), 'ABERTO', 9,
        4),
       ('Angular Forms Tutorial', 'Tutorial completo sobre formulários no Angular.', NOW(), 'ABERTO', 10, 5),
       ('Erros comuns em consultas SQL', 'Principais erros cometidos em consultas SQL e como evitá-los.', NOW(),
        'ABERTO', 11, 1),
       ('React Performance Optimization', 'Dicas para otimização de performance em aplicações React.', NOW(), 'ABERTO',
        12, 2),
       ('Desenvolvimento de aplicativos Android avançado',
        'Explorando recursos avançados para desenvolvimento de apps Android.', NOW(), 'ABERTO', 13, 3),
       ('Machine Learning com Python', 'Introdução ao Machine Learning usando Python e bibliotecas populares.', NOW(),
        'ABERTO', 14, 4),
       ('Angular Routing Guide', 'Guia completo sobre roteamento no Angular.', NOW(), 'ABERTO', 15, 5),
       ('Introduction to Java Programming', 'Discussing basic Java syntax and concepts.', '2023-06-15 10:30:00',
        'ABERTO', 1, 1),
       ('Data Analysis Techniques', 'Exploring various data analysis methods with Python.', '2023-06-16 11:45:00',
        'ABERTO', 2, 2),
       ('React Component Lifecycle', 'Understanding the lifecycle methods in React components.', '2023-06-17 12:00:00',
        'ABERTO', 3, 3),
       ('Introduction to Machine Learning', 'Overview of machine learning algorithms and applications.',
        '2023-06-18 13:15:00', 'ABERTO', 4, 4),
       ('iOS App Development Basics', 'Getting started with iOS app development using Swift.', '2023-06-19 14:30:00',
        'ABERTO', 5, 5),
       ('Cybersecurity Threats Overview', 'Discussing common cybersecurity threats and defenses.',
        '2023-06-20 15:45:00', 'ABERTO', 6, 6),
       ('Introduction to Cloud Computing', 'Basic concepts and services in cloud computing.', '2023-06-21 16:00:00',
        'ABERTO', 7, 7),
       ('UI Design Principles', 'Fundamental principles of user interface design.', '2023-06-22 17:15:00', 'ABERTO', 8,
        8),
       ('Blockchain Technology Overview', 'Exploring blockchain technology and its use cases.', '2023-06-23 18:30:00',
        'ABERTO', 9, 9),
       ('Unity Game Development Basics', 'Getting started with game development using Unity.', '2023-06-24 19:45:00',
        'ABERTO', 10, 10),
       ('Introduction to DevOps', 'Understanding the principles and practices of DevOps.', '2023-06-25 20:00:00',
        'ABERTO', 11, 11),
       ('Digital Marketing Strategies', 'Effective digital marketing strategies and techniques.', '2023-06-26 21:15:00',
        'ABERTO', 12, 12),
       ('IoT Applications and Use Cases', 'Exploring applications and use cases of IoT.', '2023-06-27 22:30:00',
        'ABERTO', 13, 13),
       ('Big Data Analytics Techniques', 'Techniques and tools for big data analysis.', '2023-06-28 23:45:00', 'ABERTO',
        14, 14),
       ('Agile Project Management Principles', 'Principles and methodologies of agile project management.',
        '2023-06-29 00:00:00', 'ABERTO', 15, 15);

-- Inserção de comentários
INSERT INTO comments (text, topic_id, created_at, user_id, solution)
VALUES ('Você verificou as configurações do seu persistence.xml?', 1, NOW(), 2, false),
       ('useState é usado para gerenciar estado em componentes funcionais, enquanto useEffect é usado para efeitos colaterais.',
        2, NOW(), 1, true),
       ('Recomendo estudar a estrutura básica de um projeto Android e explorar o Android Studio.', 3, NOW(), 3, false),
       ('Pandas é uma poderosa biblioteca para manipulação e análise de dados em Python.', 4, NOW(), 4, true),
       ('O ciclo de vida dos componentes no Angular é fundamental para entender como a aplicação funciona.', 5, NOW(),
        5, false),
       ('Certifique-se de configurar corretamente as transações no arquivo de configuração do Hibernate.', 6, NOW(), 6,
        false),
       ('Redux pode melhorar a gerência de estado em aplicações React de grande porte.', 7, NOW(), 7, true),
       ('O desenvolvimento de aplicativos iOS requer familiaridade com Swift e as diretrizes da Apple.', 8, NOW(), 8,
        false),
       ('Python oferece muitas bibliotecas poderosas para análise de dados, como Pandas e NumPy.', 9, NOW(), 9, false),
       ('Formulários são uma parte essencial do desenvolvimento web com Angular.', 10, NOW(), 7, false),
       ('Great explanation, thanks!', 1, '2023-06-15 11:00:00', 6, false),
       ('I have a question about inheritance in Java.', 1, '2023-06-15 12:30:00', 7, false),
       ('How can I optimize this algorithm?', 2, '2023-06-16 13:45:00', 8, false),
       ('I faced a similar issue last week.', 2, '2023-06-16 15:00:00', 9, false),
       ('Is React suitable for large-scale applications?', 3, '2023-06-17 16:15:00', 10, false),
       ('Can you explain the Redux workflow?', 3, '2023-06-17 17:30:00', 11, false),
       ('I implemented SVM for a project recently.', 4, '2023-06-18 18:45:00', 12, false),
       ('What are the prerequisites for machine learning?', 4, '2023-06-18 20:00:00', 13, false),
       ('How do you handle memory management in iOS apps?', 5, '2023-06-19 21:15:00', 14, false),
       ('Discussing security measures in app development.', 5, '2023-06-19 22:30:00', 15, false),
       ('How do you detect phishing attempts?', 6, '2023-06-20 23:45:00', 16, false),
       ('What are the advantages of using cloud services?', 6, '2023-06-21 01:00:00', 17, false),
       ('I have a question about UX design principles.', 7, '2023-06-21 02:15:00', 18, false),
       ('How does blockchain ensure data integrity?', 7, '2023-06-22 03:30:00', 19, false),
       ('Tips for optimizing game performance in Unity?', 8, '2023-06-22 04:45:00', 20, false),
       ('Discussing CI/CD pipelines in DevOps.', 8, '2023-06-23 06:00:00', 21, false);
